name: 'Github chen Pull Request Status Notification '
description: 'Notify when the pull request Status is changed'
author: 'mochi-sann'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node16'
  main: 'dist/index.js'
